name: Build and Release Binaries

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y make nasm

      - name: Build project
        run: make clean build

      - name: Archive binaries
        run: |
          mkdir -p dist
          cp -r bin dist/
          tar -czvf systemf-ubuntu.tar.gz -C dist bin

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: systemf-ubuntu
          path: systemf-ubuntu.tar.gz
          if-no-files-found: error

  build-debian:
    name: Build on Debian (Docker)
    runs-on: ubuntu-latest
    container:
      image: debian:stable-slim
    steps:
      - name: Install git, make and nasm
        run: apt-get update && apt-get install -y git make nasm build-essential

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build project
        run: make clean build

      - name: Archive binaries
        run: |
          mkdir -p dist
          cp -r bin dist/
          tar -czvf systemf-debian.tar.gz -C dist bin
      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: systemf-debian
          path: systemf-debian.tar.gz
          if-no-files-found: error

  build-arch:
    name: Build on Arch/Manjaro (Docker)
    runs-on: ubuntu-latest
    container:
      image: archlinux:base
    steps:
      - name: Install git, make, nasm
        run: pacman -Syu --noconfirm git make nasm

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build project
        run: make clean build

      - name: Archive binaries
        run: |
          mkdir -p dist
          cp -r bin dist/
          tar -czvf systemf-arch.tar.gz -C dist bin

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: systemf-arch
          path: systemf-arch.tar.gz
          if-no-files-found: error

  release:
    name: Upload releases
    runs-on: ubuntu-latest
    needs: [build-arch, build-debian, build-ubuntu]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v3.1
        with:
          files: |
            artifacts/systemf-arch/systemf-arch.tar.gz
            artifacts/systemf-debian/systemf-debian.tar.gz
            artifacts/systemf-ubuntu/systemf-ubuntu.tar.gz
          tag_name: "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
